# Generated by Django 4.2.6 on 2023-11-05 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vaultcollection_vaultitem_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultcollection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
